### ISSUE TITLE
How to test the tracker on OTB or VOT datasets?

### ISSUE THREAD

**Issue by yangkang779** [arbitularov/SiamRPN-PyTorch#1]
Thanks.

**Comment by arbitularov** [comment]
I have not finished the test section yet. When I finished, I will let you know (:

**Comment by yangkang779** [comment]
Many thanks.

**Comment by yangkang779** [comment]
Thanks.
I get an error when I run python train_siamrpn.py.
Epoch:0007	example:006001/1451686(0.41)%	lr:0.0005314	closs:0.3371	rloss:0.0233	tloss:0.3604
 68%|███████████████████████████             | 678/1000 [02:21<00:48,  6.71it/s]/home/yangkang/tracking/SiamRPN-PyTorch/train/data_loader.py:53: RuntimeWarning: invalid value encountered in log
  diff[:,2] = np.log((gt[2] + eps)/(anchors[:,2] + eps))
/home/yangkang/tracking/SiamRPN-PyTorch/train/data_loader.py:54: RuntimeWarning: invalid value encountered in log
  diff[:,3] = np.log((gt[3] + eps)/(anchors[:,3] + eps))
 68%|███████████████████████████▏            | 679/1000 [02:21<00:47,  6.77it/s]

**Comment by arbitularov** [comment]
I find some bounding boxes are outside of the image region. For example, in the video GOT-10k_Train_000399, at frame 66, the image size is (w=1920, h=1080), but the bounding box is [570. 477. 831. 607.], so that ymax = 477+607 = 1084 > 1080 and frame 75, the image size is (w=1920, h=1080), but the bounding box is [651.,38.,1268.,1043.0000], so that ymax = 38+1043 = 1081 > 1080. You need fixed it in your GOT-10k dataset in video GOT-10k_Train_000399 (: 👍

**Comment by yangkang779** [comment]
When will the test code be released?Many thanks.
